version: "3.9"

services:
  # Servicio para la API NestJS
  api:
    build:
      context: ./node-tree-backend
      dockerfile: Dockerfile
    container_name: nest_api
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # Servicio para la aplicación Next.js
  web:
    image: node:18-alpine
    build:
      context: ./node-tree-frontend
      dockerfile: Dockerfile
    container_name: next_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Asegurarse de que Next.js conozca la URL de la API
      - API_URL=http://api:3100
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
